### ISSUE TITLE
Define a standard for JSON flags

### ISSUE THREAD

**Issue by vincentmorneau** [OraOpenSource/apex-gulp-stack#12]
Right now we've got:
```
{
        "rest": {
            "enabled" : true,
            "port" : 443,
            "schema" : "apex_vmorneau"
        }
}
```

Should we have the enable flags outside of their respective config objects?
```
{
        "enableRest": true,
        "rest": {
            "port" : 443,
            "schema" : "apex_vmorneau"
        }
}
```

Which one is best?

**Comment by martindsouza** [comment]
If we keep the rest model, how about the presence of the `rest` attribute signals that it's enabled. Ex:

```json
{
        "rest": {
            "port" : 443,
            "schema" : "apex_vmorneau"
        }
}
```

We may want to look at providing a full URL to make it customizable (what your REST call may be will be different than someone else's)

**Comment by martindsouza** [comment]
R&D: Did not end up using this process (used cookie instead)
