### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by vincentmorneau** [OraOpenSource/apex-gulp-stack#28]
Gulp is the underlying structure of the project, not the end goal. Should be more focused on the "Front End Development" idea.

**Comment by martindsouza** [comment]
Some ideas:

- apex-frontend-dev
  - apex-fedev
- apex-web-dev-tools
  - apex-wdt
- apex-auto-refresh

**Comment by vincentmorneau** [comment]
I think we better have `frontend` in the name for explicit purposes.

I can't decide on the last part though.
- apex-frontend-toolkit
- apex-frontend-boost
- apex-frontend-lift
- apex-frontend-perfect
- apex-frontend-super or apex-super-frontend
- apex-frontend-beyond or apex-beyond-frontend

Basically I want to title to tell that this is the **best** way to develop APEX front end side. What do you think?
