### ISSUE TITLE
Create sample.json file

### ISSUE THREAD

**Issue by martindsouza** [OraOpenSource/apex-gulp-stack#3]
`config.json` should be renamed to `sample.json`. `npm install` should copy `sample.json` to `config.json` (if it doesn't already exist). This will allow users to update the project without overwriting their config.

`config.json` should be then added to `.gitignore`.

**Comment by martindsouza** [comment]
See #6 for examples on how this can be done as part of preinstall.

**Comment by vincentmorneau** [comment]
@martindsouza Please read the following (from https://docs.npmjs.com/misc/scripts):

>BEST PRACTICES
>Don't use install. Use a .gyp file for compilation, and prepublish for anything else. You should almost never have to explicitly set a preinstall or install script. If you are doing this, please consider if there is another option. The only valid use of install or preinstall scripts is for compilation which must be done on the target architecture.

Is this the solution we want to offer?

**Comment by vincentmorneau** [comment]
What if `sample.json` was in fact part of the documentation, and `config.json` contained the JSON structure, leaving out of the options to the user?

```json
{
    "javascriptConcat": {
        "enabled": true,
        "finalName": "app"
    },
    "cssConcat": {
        "enabled": true,
        "finalName": "app"
    },
    "sass": {
        "enabled": false
    },
    "browsersync": {
        "enabled": false,
        "port": 3000,
        "notify": true,
        "apexURL": "",
        "multipleDevices": false
    }
}
```

**Comment by martindsouza** [comment]
Plan: Create a `install.js` (or similar file) that will populate the `src` folder with the recommended/required folder structure.

**Comment by martindsouza** [comment]
R&D: Needed to find ways to provide a config file that won't be overwritten with each update of the project.
