### ISSUE TITLE
Detect Browsersync Usage in APEX

### ISSUE THREAD

**Issue by martindsouza** [OraOpenSource/apex-gulp-stack#5]
See if we can pass in a URL parameter so that APEX can detect that we're using browsersync. This would only be valid for first hit to APEX server.

**Comment by vincentmorneau** [comment]
What about an unrestricted application item? Like `G_APP_IMAGES` that is set on the proxy URL when Browsersync loads the app.

That would remove the need for REST I think.

**Comment by martindsouza** [comment]
Looking at passing in a value in the first call to the `REQUEST` URL parameter. Still won't resolve #10 regarding validations.

**Comment by martindsouza** [comment]
R&D Ended up using cookie
