### ISSUE TITLE
Remove dist and src folders

### ISSUE THREAD

**Issue by martindsouza** [OraOpenSource/apex-gulp-stack#6]
`dist` and `src` should be built as part of the `npm install`. Perhaps their location can be a configuration option?

**Comment by vincentmorneau** [comment]
Is it possible to generate folders as part of `npm install`?

Should we remove all sample JS, CSS and SCSS?

**Comment by martindsouza** [comment]
We can do this. See https://github.com/OraOpenSource/node4ords for an example. Specifically `package.json` and `scripts/preinstall.js`. I wrote that a long time ago and should check if better way to do this. Also need to validate it works on Windows.

**Comment by martindsouza** [comment]
Include an example folder that can be optionally installed (or just used as demo).
