### ISSUE TITLE
Clearing table browsersync_host

### ISSUE THREAD

**Issue by vincentmorneau** [OraOpenSource/apex-gulp-stack#9]
Table `browsersync_host` should be cleared periodically. Need to find a way to do so.

We should not rely on another database object (job) for this.

Maybe when inserting to the table, we also delete all records over 1 day old?

**Comment by martindsouza** [comment]
Idea: In the process that loads `browsersync_host` create a job to cleanup old items. Avoids having to create a job. Or you could have this as part of a REST request that gets fired when you do the `npm start`

**Comment by vincentmorneau** [comment]
Include it in the application process.

**Comment by martindsouza** [comment]
R&D: Did not use in end.
